.github/workflows/build.yml
recipes/mne-python_0.24/construct.yaml

It's not directly possible to deploy to `~/mne-python/VERSION` like on Linux, but this solution here is probably good enough!
Fixes #7

Deploy to ~/mne-python_VERSION on macOS

---

recipes/mne-python_0.24/construct.yaml

Several of those are still waiting to be merged into conda-forge, so this build will fail for now.
@larsoner @agramfort What's your opinion on including a set of packages commonly used by researchers in our field & scientists we know personally? I generally like the idea of including everything a user would ever need, as long as it doesn't cause us any pain. The installer packages are several 100 MBs in size already anyway, adding another 50 or 100 or even 200 doesn't make much of a difference, right? But where do we draw the line? And: do you have any suggestions for other packages that should be included? In theory, since we're using `conda`, we could even install actual tools like `git`. How far do we want to go? :)
cc @cbrnr @marsipu

Add more packages

---

.github/workflows/build.yml

This should cancel in-progress builds when a PR pushes new commits

MAINT: Use concurrency

---

recipes/mne-python_1.0/construct.yaml

cc @larsoner
Will fail until the new packages are on the CDN

Use MNE-Python 1.0.0 stable

---

.github/workflows/build.yml
recipes/mne-python_1.0/construct.yaml

It's weird that I had to change the `-eq 5` to `-eq 3` in https://github.com/mne-tools/mne-installers/pull/113. I want to check to see if it's from the `bash -e` arg, which errors out immediately on a problem (rather than allowing other commands to continue and override the exit code with something that potentially succeeds).

MAINT: Raise errors

---

.github/workflows/build.yml
recipes/mne-python_1.0/construct.yaml
tests/test_json_versions.py

Will fail until https://github.com/conda-forge/mne-feedstock/pull/93 lands and then hits CDNs later today

MAINT: Bump to 1.0.2

---

recipes/mne-python_1.0/construct.yaml

@hoechenberger I should be able to do this today:

MAINT: Bump to 1.0.3

---

.github/workflows/build.yml
README.md
assets/constructor_macOS.patch
assets/constructor_macOS_arm64.patch
assets/constructor_macOS_common.patch
assets/constructor_macOS_i386.patch
assets/post_install_macOS.sh
recipes/mne-python_1.0/construct.yaml
tools/build_local.sh
tools/extract_version.sh
tools/patch_constructor.sh
tools/run_constructor.sh
tools/setup_m1_crosscompile.sh

cc @hoechenberger currently I get conflicts when I try this locally on macOS Intel with the following on this branch (which passes the _ARG to run_installers.sh:
```console
$ source ./tools/setup_m1_crosscompile.sh
$ ./tools/run_installers.sh
```
Feel free to try it. I'm going to try doing a native run on my M1 machine with these `[not arm64]` selectors as well.
Closes #48

ENH: Build for M1

---

.github/workflows/build.yml

Now that https://github.com/conda-forge/qt-main-feedstock/pull/39 has been resolved

During automated testing, don't require system-wide installed XCB libraries anymore on Linux

---

.github/workflows/build.yml
recipes/mne-python_1.1/construct.yaml

We fixed a reported issue in the packaging: the `.jinja` files were not included in the tarball and the wheel. Oopsie 😅 
It would be nice if this bugfix release could be included in the installers for 1.1. Depends on https://github.com/conda-forge/pycrostates-feedstock/pull/4
One question, what does the operator `~=` do exactly?

Include pycrostates 0.1.2

---

recipes/mne-python_1.1/construct.yaml
tests/test_outdated.py

@larsoner This is WIP work to automatically find out which packages are potentially outdated.
My idea is to add this to a CI job to run weekly or so.
Please feel free to take over if you have time. It's already sort of useful, I suppose:
```
mne is up to date
mne-installer-menus not found on PyPI
openblas not found on PyPI
mne-qt-browser is outdated
mne-bids is up to date
mne-connectivity is up to date
mne-faster is up to date
mne-nirs is outdated
mne-realtime is outdated
mne-features is up to date
mne-rsa is outdated
mne-ari is outdated
mne-kit-gui is up to date
mne-icalabel is outdated
autoreject is up to date
pyprep is outdated
python not found on PyPI
mne-microstates is up to date
pycrostates is up to date
3 packages not found on PyPI:
[Package(name='mne-installer-menus', …
```

Update numerous bundled packages and add automated check for outdated packages

---

.github/workflows/build.yml
recipes/mne-python_1.1/construct.yaml

This won't work until @drammock cuts a 1.1.0 release on Github, conda-forge updates the feedstock, and then the CDNs update, but in the meantime I wanted to set this up so it's ready to go (restart CIs then be green hopefully!).
@hoechenberger feel free to review to make sure this is reasonable. I changed some `=0.3.1` to `~=0.3.1` since it seems like we should be okay with newer patch releases being installed, right?

MAINT: Bump to 1.1

---

.github/workflows/build.yml
tools/extract_version.sh

On https://github.com/mne-tools/mne-installers/actions/runs/3176256884/jobs/5175882589 the extended verification worked:
```
2022-10-03T18:28:11.3103387Z Verifying: .\MNE-Python-1.1.1_0-Windows.exe
2022-10-03T18:28:11.3104321Z Signature Index: 0 (Primary Signature)
2022-10-03T18:28:11.3105245Z Hash of file (sha256): 6B35806155C2098AA3531485EECA1A66D56D5FB670011FEEA6DE48FF68B43DD7
2022-10-03T18:28:11.3113330Z Signing Certificate Chain:
2022-10-03T18:28:11.3113878Z     Issued to: Certum Trusted Network CA
2022-10-03T18:28:11.3116216Z     Issued by: Certum Trusted Network CA
2022-10-03T18:28:11.3116784Z     Expires:   Mon Dec 31 12:07:37 2029
...
2022-10-03T18:28:11.3391176Z Successfully verified: .\MNE-Python-1.1.1_0-Windows.exe
2022-10-03T18:28:11.3402007Z Number of files successfully …
```

MAINT: Use extended validation for Windows builds

---

.github/workflows/build.yml
environment.yml
recipes/mne-python_1.3/construct.yaml
tests/test_outdated.py
tools/run_constructor.sh

Separate dep updates and boilerplate `_1` stuff from #168 and #173, and also make sure the installers build with the current stack

MAINT: Update deps

---

recipes/mne-python_1.4/construct.yaml
tests/test_gui.py
tests/test_imports.py
tests/test_outdated.py

- Tries 3.11
- Adds stub for Numba where we should add it once it lands
- Needs latest dev version https://github.com/conda-forge/mne-feedstock/pull/118 to land and hit CDNs (this one does not require numba)
- By that time, `mne-gui-addons` should also be in CDNs, which I've added here
- I'm trying to remove some pins for `fsleyes` and `vtk` to see if they're magically resolved
First run will undoubtedly fail, I'll restart in an hour or two

ENH: Bump versions

---

recipes/mne-python_1.4/construct.yaml

Version 0.3.0 released with improvements + compatibility for recent version of matplotlib and python.
Should be available today on conda-forge: https://github.com/conda-forge/pycrostates-feedstock/pull/9

Bump pycrostates version

---

recipes/mne-python_1.4/construct.yaml
tests/test_imports.py

To help check https://github.com/mne-tools/mne-qt-browser/issues/165
Eventually we could probably assert actual version numbers based on our pinning file and such. But for now this is good enough I think
Should fail until https://github.com/conda-forge/mne-qt-browser-feedstock/pull/24 is in and CDNs update

BUG: Add tests for setuptools_scm versions, fix mne-qt-browser

---

recipes/mne-python_1.4/construct.yaml
tests/test_outdated.py

Can't go to 3.11 yet unless we want to drop `sleepecg` and `yasa` (which needs `sleepecg`) because `sleepecg` needs Tensorflow and that is stalled at the conda end. I have no idea how widely used these packages are so I'm hesitant to remove them since we have included them previously.
Will fail until https://github.com/conda-forge/mne-feedstock/pull/122 lands and hits CDNs, at which point I'll restart CIs. I'll mark for merge-when-green then cut a release and update the MNE website with updated installer links

MAINT: Bump to 1.4.2

---

.github/workflows/build.yml
.github/workflows/outdated.yml
.github/workflows/purge_artifacts.yml
.pre-commit-config.yaml
.yamllint.yml
pyproject.toml
recipes/mne-python_0.23/construct.yaml
recipes/mne-python_0.24/construct.yaml
recipes/mne-python_1.0/construct.yaml
recipes/mne-python_1.1/construct.yaml
recipes/mne-python_1.2/construct.yaml
recipes/mne-python_1.3/construct.yaml
recipes/mne-python_1.4/construct.yaml
recipes/mne-python_1.5/construct.yaml
tests/test_gui.py
tests/test_imports.py
tests/test_json_versions.py
tests/test_notebook.py
tests/test_outdated.py

Let's make sure this builds. Draft until 1.5 lands on `conda-forge`, then we update here and merge.

MAINT: Release 1.5

---

recipes/mne-python/construct.yaml
tests/test_imports.py

Adding `mne-lsl` to the installers.
Should we keep `mne-realtime`, people mentioned it was not working with the latest version of MNE anyway?

Add mne-lsl

---

recipes/mne-python/construct.yaml
tests/test_outdated.py

Version 0.5.1 depends on `onnxruntime` instead of `pytorch`.
Closes #178
Closes #218

Bump mne-icalabel

---

recipes/mne-python/construct.yaml
tests/test_outdated.py

Required for compatibility with MNE 1.6
Feedstock update: https://github.com/conda-forge/pycrostates-feedstock/pull/11

Bump pycrostates to 0.4.0

---

recipes/mne-python/construct.yaml
tests/test_outdated.py

Draft until we can actually change to 1.6, just making sure stuff is green in the meantime

MAINT: Updates to dependencies

---

recipes/mne-python/construct.yaml
tests/test_outdated.py

Will fail until https://github.com/conda-forge/mne-feedstock/pull/126 lands and CDNs update

MAINT: Bump to 1.6.0

---

.github/workflows/build.yml
tools/macos_install_certificates.sh

Closes #232
cc @larsoner 
I would almost bet it's the `openssl` commands that are the issue; they're optional and we could just drop them for now to push out a release quickly. But let's wait and see

Add more logging output to Apple certificate workflow and ensure OpenSSL can handle our Developer certificates

---

recipes/mne-python/construct.yaml
tests/test_outdated.py

Needs https://github.com/conda-forge/mne-feedstock/pull/128 and CDN update but will mark for merge-when-green and restart CIs until it's in, then cut a 1.6.1 release here

MAINT: Bump to 1.6.1

---

recipes/mne-python/construct.yaml
tests/test_imports.py

Should maybe be upstreamed into `mne-python-feedstock`

ENH: Include pyobjc for setting name

---

recipes/mne-python/construct.yaml
tests/test_outdated.py

Empty commit to start until https://github.com/mne-tools/mne-python/pull/12666 lands, PyPI is pushed, conda-forge is updated. Then I can update to v1.7.1 here and mark for merge-when-green. In the meantime the `autofix.ci` can push an update for outdated deps and we can make sure that's green at least.

MAINT: Update to v1.7.1

---

recipes/mne-python/construct.yaml

Forgot to update the installer name from the MNE version

FIX: Installer number

---

tests/test_outdated.py

Should work since I reworked the logic recently and marked `mne-rsa` 0.91 as broken on `conda-forge`.

Check if MNE-RSA is up to date again

---

.github/workflows/build.yml

https://github.com/mne-tools/mne-installers/actions/runs/9764227628/job/26953942126 actually failed so I'll change the merge reqs to have the `Release` step required and sanity check this one by eyeballing the `ls -al ./` step

BUG: Fix bug with artifact download

---

recipes/mne-python/construct.yaml

We should explicitly have this since it's in the related software section currently.

ENH: Add picard explicitly

---

recipes/mne-python/construct.yaml
tests/test_outdated.py

I never liked having to modify `test_outdated.py` *and* `construct.yaml` when something is incompatible. This PR allows us just to update `construct.yaml` by marking *in that file* if something is out of date with an `allow_outdated` comment. So now changes and updates to dependencies can hopefully all occur in `construct.yaml` rather than being split across two files.

ENH: Track outdated allows in recipe

---

.github/workflows/build.yml
recipes/mne-python/construct.yaml
tests/test_gui.py
tests/test_imports.py
tests/test_notebook.py
tools/check_installation.sh

Rather than list a bunch of `import <mod>` lines, let's parse the YAML file and import systematically. Now imports everything in our related software list, plus a handful of custom imports of other stuff like `PySide6` and `vtk` that it seems like we wanted.

MAINT: Streamline import tests

---

recipes/mne-python/construct.yaml
tools/check_installation.sh

Have to remove `sleepecg` but I think everything else (vtk, mayavi, etc.) has been migrated. Might need CDN update though. I'll restart a few times and merge when green.

ENH: Use Python 3.13

---

.github/workflows/build.yml
recipes/mne-python/construct.yaml

Windows-2019 runner is EOL on June 30, and weekly brownouts start tomorrow.

bump windows runners
