.github/workflows/build.yml
=> Deploys build artifacts to a release when a new tag is pushed

.github/workflows/build.yml
=> Try to enable Windows build again

.github/workflows/build.yml, recipes/mne-python_0.24/mne-python_0.24.1_env.yml
=> Run CI tests for Windows installer too

README.md
It may be too early to be encouraging users to use this, so feel free to reject.
But this had the ulterior motive of checking with you that I am using the installed software in the way you intended?
=> Brief install instructions

recipes/mne-python_0.24/construct.yaml
=> Add MNE-NIRS

.github/workflows/build.yml
=> Add SHA256 hashes of release artifacts

.github/workflows/build.yml, recipes/mne-python_1.0/construct.yaml
=> Package MNE-Python 1.0 snapshot

.github/workflows/build.yml
=> Add installer package checksums to build artifacts

.github/workflows/build.yml
=> Add frozen package versions to build artifacts

assets/license.txt, recipes/mne-python_1.0/construct.yaml
=> Use plaintext license file for Linux CLI installer

.github/workflows/build.yml, assets/post_install_linux.sh, recipes/mne-python_1.0/construct.yaml
Also add a check for `.app` bundles on macOS.
=> Add postinstall script for Linux to work around bug in menuinst

.github/workflows/build.yml, assets/post_install_linux.sh, assets/post_install_macOS.sh, assets/post_install_windows.bat, recipes/mne-python_1.0/construct.yaml
=> Prevent using local user-installed packages

.github/workflows/build.yml, recipes/mne-python_1.0/construct.yaml
Let's see if dipy 3.10 is likely to fix our problems or if there is something else we can know in advance we need to investigate
=> MAINT: Fix conditionals for PRs

recipes/mne-python_1.0/construct.yaml, tests/test_imports.py
=> ENH: add pyprep

.github/workflows/build.yml, assets/constructor_macOS.patch
=> Don't display AppleScript notifications on macOS

.github/workflows/build.yml, assets/constructor_macOS.patch, assets/post_install_macOS.sh, recipes/mne-python_1.0/construct.yaml
=> On macOS, install to /Applications/MNE-Python

.github/workflows/build.yml, assets/constructor_macOS.patch, assets/post_install_macOS.sh
=> Install conda environment on macOS into "hidden" directory

assets/post_install_macOS.sh, recipes/mne-python_1.0/construct.yaml
=> Use latest mne and mne-installer-menus packages

recipes/mne-python_1.0/construct.yaml
Will hopefully pick up https://github.com/conda-forge/mne-feedstock/pull/88 once CDNs update. Then we could test on all platforms, cut a new v1.0.0_1 release, and update MNE-Python docs again.
=> ENH: Use better launchers

recipes/mne-python_1.0/construct.yaml, tests/test_imports.py
=> Include sleepecg

.github/workflows/build.yml, recipes/mne-python_1.0/construct.yaml
=> Use mne-qt-browser 0.2.6

recipes/mne-python_1.0/construct.yaml, tests/test_gui.py
Once merged, we can tag a new release!
=> Update mne-qt-browser to version 0.3

recipes/mne-python_1.0/construct.yaml, tests/test_json_versions.py
=> Include pqdm

.bulldozer.yml
I just installed https://github.com/apps/prylabs-bulldozer in this repo and added an `automerge` label to this PR. Let's see if it works.
=> CI: Add automerge

.github/workflows/build.yml, tests/test_json_versions.py, tools/extract_version.sh
=> ENH: Split and persist CI jobs & artifacts

.github/workflows/build.yml, assets/post_install_linux.sh, assets/post_install_macOS.sh, assets/post_install_windows.bat, tests/test_gui.py, tests/test_gui_macosx.py
=> Use the Qt-based Matplotlib backend by default on macOS

recipes/mne-python_1.1/construct.yaml, tests/test_imports.py
Closes https://github.com/vferat/pycrostates/issues/50
That was simple enough, anything missing?
=> Include pycrostates

recipes/mne-python_1.1/construct.yaml
Builds will fail until https://github.com/conda-forge/mne-feedstock/pull/103 hits the CDN
cc @larsoner
=> Fix OpenBLAS issue on M1 and bump MNE to latest main snapshot

.github/workflows/outdated.yml, recipes/mne-python_1.1/construct.yaml, tests/test_outdated.py
Will require https://github.com/conda-forge/mne-feedstock/pull/106 and CDN update but let's get the ball rolling
=> MAINT: Bump to 1.1.1

recipes/mne-python_1.3/construct.yaml
=> Include pyRiemann

recipes/mne-python_1.3/construct.yaml
Needs https://github.com/conda-forge/mne-feedstock/pull/115 but I'll get it going now so I can merge it when CIs are green
Closes #179
=> MAINT: Bump to 1.3.1

recipes/mne-python_1.4/construct.yaml
I missed these when working on Windows recently. Also update outdated dependencies.
=> ENH: Add git and make for Windows

.github/workflows/build.yml, recipes/mne-python_1.5/construct.yaml, tests/test_outdated.py
1. Add profiling tools for developer use.
2. Update deps.
3. Remove windows signing. It was too expensive and it's easy enough on Windows to say "install anyway" (much easier than on macOS).
=> ENH: Add profiling tools

.github/workflows/build.yml, recipes/mne-python/construct.yaml, tests/test_dev_installed.py, tests/test_imports.py, tests/test_outdated.py, tools/calculate_installer_hash.sh, tools/check_installation.sh, tools/export_frozen_env_def.sh, tools/extract_version.sh, tools/macos_check_installer_signature.sh, tools/macos_install_certificates.sh, tools/macos_notarize_installer.sh
Related to https://github.com/mne-tools/mne-python/issues/11831. We should check that `mne[test,test_extra,full,doc]` is installed by our installer.
Will fail until https://github.com/mne-tools/mne-python/pull/12209 is merged, should say something like:
```
AssertionError: Unexpected unmet dependencies:
Sphinx-6.2.1
mne-bids-0.14.dev0
mne-connectivity-0.6.0.dev0
mne-gui-addons-0.2.0.dev9+gc245654
pydata-sphinx-theme-0.13.3
sphinx-gallery-0.15.dev0
```
=> MAINT: Check against mne pip option

recipes/mne-python/construct.yaml
Already available on `conda-forge`, surprisingly quick.
=> Bump pycrostates and mne-lsl

environment.yml, recipes/mne-python/construct.yaml, tools/extract_version.sh, tools/macos_check_installer_signature.sh
=> MAINT: Remove bundle_tools_3

recipes/mne-python/construct.yaml
Let's bump to latest versions to make sure the build still works in anticipation of 1.7 release
=> MAINT: Bump versions

recipes/mne-python/construct.yaml
=> ENH: Make related software list explicit

recipes/mne-python/construct.yaml
Needs https://github.com/conda-forge/mne-feedstock/pull/138 but let's get the package updates going anyway
=> MAINT: Bump to 1.8.0

environment.yml, recipes/mne-python/construct.yaml, tests/test_imports.py
- xref https://github.com/sappelhoff/eeg_positions/issues/25
=> add eeg_positions

recipes/mne-python/construct.yaml, tests/test_dev_installed.py
Let's get everything as up to date as we can so that once we cut 1.9 it's hopefully uncomplicated to cut a release here :sweat_smile:
=> ENH: Update deps

recipes/mne-python/construct.yaml
Needs https://github.com/openmeeg/openmeeg/actions/runs/12381332900 then https://github.com/conda-forge/openmeeg-feedstock/pull/65 then CDNs
=> MAINT: Bump openmeeg

.pre-commit-config.yaml, recipes/mne-python/construct.yaml
Closes #315
Needs https://github.com/conda-forge/mne-feedstock/pull/141
=> MAINT: Bump to 1.9.0

recipes/mne-python/construct.yaml
... and document others we can't install.
=> ENH: Add alphacsc

mne-installer-menu/meta.yaml, recipes/mne-python/construct.yaml, tools/check_installation.sh
Needs https://github.com/conda-forge/mne-feedstock/pull/143. Will restart CIs until green, merge, and cut a release.
=> MAINT: Bump to 1.10.0
